name: "BEC Launcher Install"
description: "Install BEC Launcher and related os dependencies"
inputs:
  BEC_LAUNCHER_BRANCH: # id of input
    required: false
    default: "main"
    description: "Branch of BEC Launcher to install"
  PYTHON_VERSION: # id of input
    required: false
    default: "3.11"
    description: "Python version to use"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Checkout BEC Core
      uses: actions/checkout@v4
      with:
        repository: bec-project/bec_launcher
        ref: ${{ inputs.BEC_LAUNCHER_BRANCH }}
        path: ./bec_launcher

    - name: Install Python dependencies
      shell: bash
      run: |
        pip install uv
        uv pip install --system -e ./bec_launcher[dev]
